name: interntask
description: "The intern task with Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: TTNorms
      fonts:
        - asset: assets/fonts/TT-norms/TTNorms-Bold.otf
          weight: 700
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-bold/Gilroy-Bold.ttf
    - family: Europa
      fonts:
        - asset: assets/fonts/Europa/europa.ttf


